### PR TITLE
index.d.ts added and import fixes

### PR DESCRIPTION
**Pull request by brunocrpontes**
# Summary

Adding `index.d.ts` to project to handle exports from typescript projects and fixing the imports from `./src/` instead of `./lib/`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by jsamr** [comment]
@brunocrpontes Any updates ? That would be really cool!

PS : I also happen to live in Juazeiro!

**Comment by brunocrpontes** [comment]
HAHAHA, really @jsamr?

I already added the file types and imports, if you need really need to use it, just use my branch as version in your ```package.json```.

About some updates I'm waiting to somebody does the review and comment the necessary updates to be merged.

**Comment by jsamr** [comment]
@brunocrpontes Well yeah, just moved in September with my wife. Santiago Residence, Av. Padre Cisero. Can email me if you're curious!

**Comment by pvinis** [comment]
I guess we can close this now, right? We moved to ts succesfully, so no need for manual d.ts files.

**Comment by brunocrpontes** [comment]
@pvinis sure!

**Pull request closed without merging**
